// Generated by CoffeeScript 1.8.0
(function() {
  var childProcess, os;

  os = require('os');

  childProcess = require('child_process');

  module.exports = {
    publish: function(type, domain, port) {
      var child, name;
      name = os.hostname().replace(/\.local\.?$/, '');
      try {
        return child = (function() {
          switch (process.platform) {
            case "darwin":
              return childProcess.spawn('dns-sd', ['-R', name, type, domain, port]);
            case "win32":
            case "win64":
              return childProcess.spawn('dns-sd', ['-R', name, type, domain, port]);
            case "linux":
              return childProcess.spawn('avahi-publish-service', [name, "" + type + "._tcp", port]);
            default:
              return console.warn("Plateform not supported");
          }
        })();
      } catch (_error) {
        return print("Veuillez installer mDNS");
      }
    }
  };

}).call(this);
